LEXICON_COMMANDS_RU: dict[str, str] = {
    '/start': 'Запустить бота',
    '/admin': 'Админ-панель',
}

LEXICON_RU: dict[str, str| dict[str, str]] = {
    '/start': 'Привет! Я бот для расчета стоимости авто',
    'main_menu': 'Выберите один из пунктов',
    'car_link': 'Ссылка на авто',
    'calculator': 'Калькулятор',
    'exchange_rates': 'Курс валют',
    'calculate_by_url': 'Рассчитать по ссылке',
    'enter_url': 'Пожалуйста, отправьте ссылку на страницу с автомобилем',
    'select_year': 'Выберите период выпуска авто',
    'year_less_3': 'Младше 3х лет',
    'year_3_5': 'От 3 до 5 лет',
    'year_more_5': 'Старше 5 лет',
    'select_currency': 'Выберите валюту для ввода стоимости',
    'rub': 'Рубли',
    'eur': 'Евро',
    'usd': 'Доллары',
    'cny': 'Юани',
    'krw': 'Воны',
    'enter_cost': 'Напишите стоимость авто (пример: 5000000)',
    'select_volume': 'Введите объем двигателя в куб. см. (например: 2000)',
    'back': 'Назад',
    'exit': 'Выход',
    'calculation_params': 'Параметры рассчёта',
    'car_age': 'Возраст авто',
    'car_cost': 'Стоимость авто',
    'engine_volume': 'Объём двигателя',
    'total_cost': 'Итоговая стоимость',
    'exit_message': 'Вы вышли из калькулятора',
    'not_a_number': 'Вы ввели не число. Пожалуйста, введите стоимость числом.',
    'korea_dealer_commission': 'Комиссия дилера в Корее',
    'customs_payments': 'Таможенные пошлина',
    'recycling_fee': 'Утилизационный сбор',
    'customs_clearance': 'Таможенный сбор',
    'sbkts_and_epts': 'СБКТС и ЭПТС',
    'loading_and_unloading_and_temporary_storage': 'Погрузочно-разгрузочные работы и СВХ',
    'ferry': 'Перегон',
    'other_expenses': 'Прочие расходы',
    'rates_message': 'Курс валют к рублю:',
    'calculate_another_car': 'Рассчитать стоимость другой машины',
    'select_engine_type': 'Выберите тип двигателя',
    'petrol_diesel': 'Бензин/Дизель',
    'electric_hybrid': 'Электро/послед.гибрид',
    'engine_type_label': 'Тип двигателя',
    'ice': 'ДВС',
    'electro': 'Электро',
    'hybrid_info': 'Последовательные гибриды расчитываются как электро, а остальные гибриды как ДВС',
    'vat': 'НДС',
    'subscription_required': 'Для доступа к боту необходимо подписаться на канал.',
    'channel_button': 'Подписаться',
    'admin_panel': 'Админ-панель',
    'edit_params': 'Редактировать параметры',
    'enter_new_value': 'Введите новое значение для',
    'value_updated': 'Значение обновлено',
    'exit_admin': 'Выйти из админ-панели',
    'calc_config_fields': {
        'korea_dealer_commission': 'Комиссия дилера в Корее',
        'sbkts_and_epts': 'СБКТС и ЭПТС',
        'loading_and_unloading_and_temporary_storage': 'Погрузочно-разгрузочные работы и СВХ',
        'ferry': 'Перегон',
        'other_expenses': 'Прочие расходы',
    }
}
